### ISSUE TITLE
UnboundLocalError: local variable 'optimizer_pose' referenced before assignment

### ISSUE THREAD

**Issue by WithFoxSquirrel** [facebookresearch/robust-dynrf#12]
When i run train.py,  error occur
```
Traceback (most recent call last):
  File "train.py", line 2675, in <module>
    reconstruction(args)
  File "train.py", line 2609, in reconstruction
    optimizer_pose.param_groups[0]["lr"] = 0.0
```

UnboundLocalError: local variable 'optimizer_pose' referenced before assignment

**Comment by cv-lab-x** [comment]
@WithFoxSquirrel hi, have you solved this issue? same error with yours

**Comment by Drow999** [comment]
The same! I think it's because in the configs/Nvidia.txt, 'optimize.poses' is equal to 0.

**Comment by WithFoxSquirrel** [comment]
> @WithFoxSquirrel hi, have you solved this issue? same error with yours

not yet

**Comment by jeff999955** [comment]
This patch works for me

```
diff --git a/train.py b/train.py
index 8941eed..c7bd16c 100644
--- a/train.py
+++ b/train.py
@@ -2610,8 +2610,10 @@ def reconstruction(args):
             optimizer = torch.optim.Adam(grad_vars, betas=(0.9, 0.99))
 
         if iteration > args.n_iters // 2:
-            optimizer_pose.param_groups[0]["lr"] = 0.0
-            optimizer_focal.param_groups[0]["lr"] = 0.0
+            if args.optimize_poses:
+                optimizer_pose.param_groups[0]["lr"] = 0.0
+            if args.optimize_focal_length:
+                optimizer_focal.param_groups[0]["lr"] = 0.0
 
     tensorf.save(
         poses_mtx.detach().cpu(),
```
