### ISSUE TITLE
error when training the model

### ISSUE THREAD

**Issue by ty1erz** [facebookresearch/robust-dynrf#15]
rain.py:1301: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, args.batch_size - 1, dtype=torch.int64)[:, None],
Using C:\Users\tianyue.zhang\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117 as PyTorch extensions root...
C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\tianyue.zhang\AppData\Local\torch_extensions\torch_extensions\Cache\py38_cu117\segment_cumsum_cuda\build.ninja...
信息: 用提供的模式无法找到文件。
  0%|                                                                                                                                                                                  | 0/100000 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 2675, in <module>
    reconstruction(args)
  File "train.py", line 1304, in reconstruction
    loss_distortion = flatten_eff_distloss(
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch_efficient_distloss\eff_distloss.py", line 93, in forward
    segment_cumsum_cuda = load(
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\utils\cpp_extension.py", line 1611, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\utils\cpp_extension.py", line 2048, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\site-packages\torch\utils\cpp_extension.py", line 2188, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\tianyue.zhang\.conda\envs\RoDynRF\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by sunkaifan** [comment]
I have the same problem with you, and now it is solved. You should check you environment whether you are in pytorch 2.0 and cuda 11.7.

**Comment by skf-1999** [comment]
I have the same problem with you.
I install Visual Studio 2022 to get cl.exe.
call your environment\VC\Auxiliary\Build\vcvars64.bat
set path cl.exe
Then code is running.

**Comment by skf-1999** [comment]
If you system is windows, you need to change system coding ways all utf8, or all gbk.

**Comment by Gloryseven** [comment]
#8
