### ISSUE TITLE
when training i met a problem

### ISSUE THREAD

**Issue by weiya-89** [facebookresearch/robust-dynrf#5]
hi，nice work. when training i met a problem

Traceback (most recent call last):
  File "/home/vision/work/lzw/robust-dynrf-main/train.py", line 2675, in <module>
    reconstruction(args)
  File "/home/vision/work/lzw/robust-dynrf-main/train.py", line 2447, in reconstruction
    ) = render(
  File "/home/vision/work/anaconda3/envs/RoDynRF/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/vision/work/lzw/robust-dynrf-main/renderer.py", line 488, in render
    scene_flow_f, scene_flow_b = tensorf.module.get_forward_backward_scene_flow(
  File "/home/vision/work/anaconda3/envs/RoDynRF/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TensorVMSplit_TimeEmbedding' object has no attribute 'module'

**Comment by xiazhi1** [comment]
Same Bug for me,have you solved it?

**Comment by weiya-89** [comment]
i delete the module in renderer.py in line 488 like this and it works, But I don't know if this will affect the results

scene_flow_f, scene_flow_b = tensorf.get_forward_backward_scene_flow(
 pts_ref, ts_chunk
)

**Comment by xiazhi1** [comment]
> i delete the module in renderer.py in line 488 like this and it works, But I don't know if this will affect the results scene_flow_f, scene_flow_b = tensorf.get_forward_backward_scene_flow( pts_ref, ts_chunk )

Thanks a lot ! It works for me!

**Comment by Gloryseven** [comment]
> i delete the module in renderer.py in line 488 like this and it works, But I don't know if this will affect the results scene_flow_f, scene_flow_b = tensorf.get_forward_backward_scene_flow( pts_ref, ts_chunk )

Do you mean to delete lines from 488 to 503?
